### ISSUE TITLE
intermittent transport timeouts retrial in Java CIFS

### ISSUE THREAD

**Issue by GodofGurus** [JetBrains/teamcity-deployer-plugin#78]
I have been noticing intermittent failure with plugin causing builds to fail when attempting to write:

 [Step 22/23] jcifs.smb.SmbException: Transport1 timedout waiting for response to SmbComWriteAndX[command=SMB_COM_WRITE_ANDX,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=1,pid=58421,uid=1,mid=6617,wordCount=14,byteCount=16575,andxCommand=0xFF,andxOffset=0,fid=10,offset=1634012888,writeMode=0,remaining=700522,dataLength=16574,dataOffset=64]
jcifs.util.transport.TransportException: Transport1 timedout waiting for response to SmbComWriteAndX[command=SMB_COM_WRITE_ANDX,received=false,errorCode=0,flags=0x0018,flags2=0xC803,signSeq=0,tid=1,pid=58421,uid=1,mid=6617,wordCount=14,byteCount=16575,andxCommand=0xFF,andxOffset=0,fid=10,offset=1634012888,writeMode=0,remaining=700522,dataLength=16574,dataOffset=64]
	at jcifs.util.transport.Transport.sendrecv(Transport.java:73)
	at jcifs.smb.SmbTransport.send(SmbTransport.java:655)
	at jcifs.smb.SmbSession.send(SmbSession.java:238)
	at jcifs.smb.SmbTree.send(SmbTree.java:119)
	at jcifs.smb.SmbFile.send(SmbFile.java:775)
	at jcifs.smb.SmbFileOutputStream.writeDirect(SmbFileOutputStream.java:245)
	at jcifs.smb.SmbFileOutputStream.write(SmbFileOutputStream.java:216)
	at jetbrains.buildServer.deployer.agent.smb.SMBBuildProcessAdapter.copyInterruptibly(SMBBuildProcessAdapter.java:147)
	at jetbrains.buildServer.deployer.agent.smb.SMBBuildProcessAdapter.upload(SMBBuildProcessAdapter.java:130)
	at jetbrains.buildServer.deployer.agent.smb.SMBBuildProcessAdapter.runProcess(SMBBuildProcessAdapter.java:90)
	at jetbrains.buildServer.deployer.agent.SyncBuildProcessAdapter.start(SyncBuildProcessAdapter.java:58)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:70)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:50)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:288)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:53)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:252)
	at java.lang.Thread.run(Thread.java:745)

**Comment by GodofGurus** [comment]
maybe you can add retrials
