### ISSUE TITLE
Failed to connect via SMB protocol.

### ISSUE THREAD

**Issue by Ruslan878** [JetBrains/teamcity-deployer-plugin#97]
Hi. I've tried to upload files via SMB protocol, but I've gotten the error:

Step 3/3: Upload build to a Network Share (SMB Upload) (7s)
[04:11:21]	[Step 3/3] Starting upload via SMB to \\someServerName\SomeShareFolder
[04:11:28]	[Step 3/3] jcifs.smb.SmbException: Failed to connect: someServerName/192.***.4.***
jcifs.util.transport.TransportException
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at jcifs.util.transport.Transport.readn(Transport.java:29)
	at jcifs.smb.SmbTransport.peekKey(SmbTransport.java:388)
	at jcifs.smb.SmbTransport.negotiate(SmbTransport.java:288)
	at jcifs.smb.SmbTransport.doConnect(SmbTransport.java:319)
	at jcifs.util.transport.Transport.run(Transport.java:241)
	at java.lang.Thread.run(Thread.java:745)
	at jcifs.util.transport.Transport.run(Transport.java:258)
	at java.lang.Thread.run(Thread.java:745)
[04:11:28]	[Step 3/3] Step Upload build to a Network Share (SMB Upload) failed

TeamCity server and Build Agent are installed on the same server. TeamCity Professional 2017.1.4 (build 47070).

Build Step settings:
![build configuration teamcity - google chrome 2017-10-25 11 29 58](https://user-images.githubusercontent.com/20335464/31988502-00088a2a-b978-11e7-97d3-46979e2294bc.png)

I've checked SMB1 protocol on both servers. It's enabled.
The server with installed TeamCity Build Agent and TeamCity server(OS Windows 10 ):
![teamcity srv](https://user-images.githubusercontent.com/20335464/31988789-ea3105fa-b978-11e7-848a-e180d8b5892f.png)

The server with SMB share folder (OS Windows Server 2012 ):
![share server](https://user-images.githubusercontent.com/20335464/31988865-314a370e-b979-11e7-9883-af0399f16b67.png)

In manual mode, all work ok. I successfully copy files from one server to another server into SMB share folder. What is the cause of the problem?

**Comment by Ruslan878** [comment]
I'm sorry. SMB protocol is disabled on the local network on the router level.
