### ISSUE TITLE
SSH deployer authentication failure with transport protocol SFTP

### ISSUE THREAD

**Issue by aswamca** [JetBrains/teamcity-deployer-plugin#98]
Questions:
My requirement is to deploy the artifacts (created in teamcity while compiling the code) via teamcity to dev server through ssh deployer using SFTP ,  my build agent is runing on windows machine and i am trying to deploy artifact on linux machine 

how to get ride of the auth fail?
Please specify with some examples how each deployers are working?
I am using my credential for deployment 

below is the error:

Deploymnent Package (SSH Deployer) (3s)
[11:42:41][Step 4/4] com.jcraft.jsch.JSchException: Auth fail
[11:42:41][Step 4/4] com.jcraft.jsch.JSchException: Auth fail
     at com.jcraft.jsch.Session.connect(Session.java:512)
     at com.jcraft.jsch.Session.connect(Session.java:183)
     at jetbrains.buildServer.deployer.agent.ssh.SSHSessionProvider.<init>(SSHSessionProvider.java:102)
     at jetbrains.buildServer.deployer.agent.ssh.SSHDeployerRunner.getDeployerProcess(SSHDeployerRunner.java:44)
     at jetbrains.buildServer.deployer.agent.base.BaseDeployerRunner.createBuildProcess(BaseDeployerRunner.java:47)
     at jetbrains.buildServer.agent.impl.runner.CallRunnerService.doCreateBuildProcess(CallRunnerService.java:71)
     at jetbrains.buildServer.agent.impl.runner.CallRunnerService.createBuildProcess(CallRunnerService.java:47)
     at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:47)
     at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
     at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
     at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
     at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
     at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
     at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
     at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
     at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
     at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
     at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
     at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
     at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
     at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
     at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
     at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
     at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
     at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:70)
     at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:50)
     at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:288)
     at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:53)
     at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:252)
     at java.lang.Thread.run(Thread.java:722)
[11:42:41][Step 4/4] Step Deploymnent Package (SSH Deployer) failed with unexpected error

**Comment by nskvortsov** [comment]
1. Select "verbose" messages level on build log tab to see exact SSH messages exchange. This will tell, why auth fails.
2. Check, that `password` auth type is allowed by ssh server, `keyboard-interactive` is not enough.

**Comment by aswamca** [comment]
Hi ,

password auth type is already allowed by ssh server.

I have enabled the "verbose" and still deployment is failing now we are getting below error

Step 4/4: Deploymnent Package (SSH Deployer) (3s)
[06:24:36][Step 4/4] ##teamcity[buildStatisticValue key='buildStageDuration:firstStepPreparation' value='62.0']
[06:24:36][Step 4/4] ##teamcity[buildStatisticValue key='buildStageDuration:buildStepRUNNER_1567' value='0.0']
[06:24:39][Step 4/4] com.jcraft.jsch.JSchException: Auth fail
[06:24:39]
[Step 4/4] com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at jetbrains.buildServer.deployer.agent.ssh.SSHSessionProvider.<init>(SSHSessionProvider.java:102)
	at jetbrains.buildServer.deployer.agent.ssh.SSHDeployerRunner.getDeployerProcess(SSHDeployerRunner.java:44)
	at jetbrains.buildServer.deployer.agent.base.BaseDeployerRunner.createBuildProcess(BaseDeployerRunner.java:47)
	at jetbrains.buildServer.agent.impl.runner.CallRunnerService.doCreateBuildProcess(CallRunnerService.java:71)
	at jetbrains.buildServer.agent.impl.runner.CallRunnerService.createBuildProcess(CallRunnerService.java:47)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:47)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:70)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:50)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:288)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:53)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:252)
	at java.lang.Thread.run(Thread.java:722)
[06:24:39][Step 4/4] ##teamcity[buildStatisticValue key='buildStageDuration:buildStepRUNNER_1567' value='3157.0']
[06:24:39][Step 4/4] Step Deploymnent Package (SSH Deployer) failed with unexpected error
[06:24:39]##teamcity[buildStatisticValue key='buildStageDuration:buildFinishing' value='15.0']
[06:24:39]Publishing internal artifacts
[06:24:39]##teamcity[buildStatisticValue key='buildStageDuration:artifactsPublishing' value='125.0']

**Comment by aswamca** [comment]
Please help , need urgently.. Thanks in advance

**Comment by nskvortsov** [comment]
@aswamca 
* go to build results, 
* open build "Build Log" tab
* select "Verbose" in "View" combobox
* find the SSH debug messages in build log (should have appeared)
* post them here.

If no SSH debug messages are present in build log after choosing "Verbose", please update the plugin or consult the logs of SSH server

**Comment by aswamca** [comment]
Hi According you SSH server is target location ,where through winscp I am able to upload files on target location . So what message you are trying to look here ..
We have sent verbose log only to you, Please let us  know why this authentication stopping ??
Thanks

**Comment by nskvortsov** [comment]
The verbose log that you sent does not contain SSH debug messages
It means, you are using old version of plugin or TeamCity server. 

Please install a latest version of the plugin available [here](http://teamcity.jetbrains.com/repository/download/TeamCityPluginsByJetBrains_Deployment_DeploymentPlugin10x/.lastPinned/deploy-runner.zip?guest=1) using [this instruction](https://confluence.jetbrains.com/display/TCD10/Installing+Additional+Plugins)

Then try again and look for debug messages.

**Comment by StevenLiSiwei** [comment]
I am getting the same error using teamcity 2018.2.2. I followed @nskvortsov instructions but it didn't help.
`[20:46:54]	Step 3/4: Deploy (SSH Upload)
[20:46:55]	[Step 3/4] Deployment problem: Auth fail
[20:46:55]	[Step 3/4] Step Deploy (SSH Upload) failed`
